config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'terms_of_use' => 'homes#terms_of_use'
  devise_for :end_users
  resources :end_users, only: [:index, :show, :edit, :update] do
    member do
      get 'mypage/:id' => 'end_users#mypage', as: 'mypage'
      get 'my_favorite/:id' => 'end_users#my_favorite', as: 'my_favorite'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :records, only: [:index, :show, :edit, :update, :create, :new, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :rooms

  resources :contacts, only: [:new, :create] do
    collection do
      post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
      post 'contacts/back' => 'contacts#back', as: 'back'
      get 'done' => 'contacts#done', as: 'done'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :email, presence: true
  validates :message, presence: true, length: { minimum: 2, maximum: 500 }
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :end_user
  belongs_to :room

  after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  default_scope -> { order(created_at: :desc) }

  has_many :records, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries

  # 自分がフォローされる側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー、フォロワー一覧機能実装の為
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 500 }

  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  # end_userのindexページで検索
  def self.search(keyword)
    if keyword == ''
      all
    else
      where(["name like?", "%#{keyword}%"])
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :record
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user
  belongs_to :record

  validates :comment, presence: true, length: { minimum: 1, maximum: 100 }
end

app/models/record.rb
class Record < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :artist_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :genre, presence: true
  validates :introduction, presence: true, length: { minimum: 2, maximum: 500 }
  validates :release_date, presence: true

  attachment :image

  enum genre: { pops: 0, rock: 1, black_music: 2, edm: 3, classic: 4, jazz: 5 }

  # いいね済みかどうか確認する
  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  # def self.record_search(keyword)
  #   where(["title like? OR introduction like? OR artist_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  # end

  # rcordのindexページの検索
  def self.search(keyword)
    if keyword == ''
      all
    else
      where(["title like? OR introduction like? OR artist_name like? OR genre like? OR release_date like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :end_users, through: :entries
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if end_user_signed_in?
      redirect_to mypage_path(current_end_user.id)
    end
  end

  def terms_of_use
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_end_user!

  def index
    keyword = params[:keyword]
    @records = Record.search(keyword)
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    @record.save ? (redirect_to mypage_end_user_path(current_end_user.id)) : (render :new)
  end

  def show
    @record = Record.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = PostComment.includes([:record, :end_user]).where(record_id: @record.id)
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    @record.update(record_params) ? (redirect_to record_path(@record.id)) : (render :edit)
  end

  def destroy
    record = Record.find(params[:id])
    record.destroy
    redirect_to mypage_end_user_path(current_end_user.id)
  end

  private

  def record_params
    params.require(:record).permit(:title, :image, :artist_name, :genre, :introduction, :release_date, :end_user_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_end_user!

  def index
    @end_user = current_end_user
    @current_entries = @end_user.entries.includes([:room])
    my_room_ids = []
    @current_entries.each do |entry|
      my_room_ids << entry.room.id
    end
    @another_entries =
      Entry.includes([:room, :end_user]).where(room_id: my_room_ids).where.not(end_user_id: @end_user.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:end_user_id => current_end_user.id, :room_id => @room.id).present?
      @direct_messages = @room.direct_messages.includes([:end_user])
      @entries = @room.entries.includes([:end_user])
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(:name => "DM")
    @entry1 = Entry.create(:room_id => @room.id, :end_user_id => current_end_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:end_user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room.id)
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to request.referer
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/records/_error_message.html.erb
  <div class="error-message">
    <% if @record.errors.any? %>
      入力内容を確認してください
    <% end %>
  </div>

app/views/records/_index.html.erb
<% records.each do |record| %>
  <%= link_to record_path(record.id), class: "my-record" do %>
    <%= attachment_image_tag record, :image, fallback: "no-image.png", size:'200x200', class: "m-1 record record-image" %>
  <% end %>
<% end %>

app/views/records/edit.html.erb
<div class="main-container text-white text-center">

  <%= render 'records/error_message' %>

  <%= form_with model: @record, local:true do |f| %>
    <div class="form-group form-group-lg mt-5 text-center">
      <p><img id="preview"></p>
      <p><%= attachment_image_tag @record, :image, fallback: "no-image.png", size: '180x180', id: "existing_file" %></p>
      <p class="text-center"><%= f.attachment_field :image %></p>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_field :title, placeholder: "タイトル", class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_field :artist_name, placeholder: "アーティスト名", class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_area :introduction, placeholder: "感想や思い出、詳細情報", class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <% t = Time.now %>
      <%= f.date_select :release_date, {:discard_month => true, :start_year => 1900, :end_year => t.year}, class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.select :genre, Record.genres.keys.to_a, { include_blank: 'ジャンル'}, {class: "col-form-label rounded-pill col-sm-6"} %>
    </div>
    <div>
      <%= image_submit_tag("change-icon.png", id: "edit_record_button") %>
    </div>

  <% end %>
</div>

<script>
  $('#record_image').on('change', function (e) {
    let reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
        $("#existing_file").hide();
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/records/index.html.erb
<div class="text-center record-index main-container text-white">
  <h4 class="text-center mb-3"><%= link_to "ユーザ一覧", end_users_path, class: "text-white"%></h4>
    <%= form_with url: records_path, method: :get do |f| %>
      <div class="text-right form-group form-group-lg">
        <%= f.text_field :keyword, value: @keyword, class: "col-form-label border-0 rounded-pill col-sm-4 search_word" %>
        <%= f.submit "検索", class: "btn btn-outline-light search-btn" %>
      </div>
    <% end %>
  <div class="d-flex justify-content-center align-content-start flex-wrap search-record">
    <%= render 'index', records: @records %>
  </div>
</div>

app/views/records/index.js.erb
$('.search-record').html('<%= j(render 'index', records: @records) %>');

app/views/records/new.html.erb
<div class="main-container text-white text-center">

  <%= render 'records/error_message' %>

  <%= form_with model: @record, local:true do |f| %>
    <div class="form-group form-group-lg mt-5 text-center">
      <p><img id="preview"></p>
      <p><%= f.attachment_field :image %></p>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_field :title, placeholder: "タイトル", class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_field :artist_name, placeholder: "アーティスト名", class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_area :introduction, placeholder: "感想や思い出、詳細情報", class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <% t = Time.now %>
      <%= f.date_select :release_date, {:discard_month => true, :start_year => 1900, :end_year => t.year}, class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.select :genre, Record.genres.keys.to_a, { include_blank: 'ジャンル' }, {class: "col-form-label rounded-pill col-sm-6"} %>
    </div>
    <%= f.hidden_field :end_user_id, :value => current_end_user.id %>
    <div>
      <%= image_submit_tag("collected-icon.png", id: "new_record_button") %>
    </div>

  <% end %>
</div>

<script>
  $('#record_image').on('change', function (e) {
    let reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
        $("#existing_file").hide();
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/records/show.html.erb
<div class="main-container mt-3">
  <div class="row">
    <div class="col-6 text-center  mb-5">
      <div class="mb-3">
        <%= link_to end_user_path(@record.end_user_id), class: "contributor_name" do %>
        <%= attachment_image_tag @record.end_user, :profile_image, fallback: "no-image2.jpg", size:'50x50', class: "rounded-circle" %>
        <% end %>
        <%= link_to @record.end_user.name, end_user_path(@record.end_user_id), class: "contributor_name" %>
      </div>
      <p><%= attachment_image_tag @record, :image, fallback: "no-image.png", size:'300x300', class: "show-record" %></p>
      <% if @record.end_user == current_end_user %>
        <%= link_to "編集", edit_record_path(@record.id), class: "text-white" %>
        <%= link_to "削除", record_path(@record.id), method: :delete, class: "text-white" %>
      <% end %>
    </div>
    <div class="col-6 text-white mt-5">
      <h3 class="d-inline sp-fontsize"><%= @record.title %></h3>
      <div id="favorites_buttons_<%= @record.id %>", class="d-inline ml-2">
        <%= render partial: 'favorites/favorite', locals: { record: @record } %>
      </div>
      <h3 class="mt-3 sp-fontsize"><%= @record.artist_name %></h3>
      <p class="sp-fontsize-p"><%= @record.release_date.strftime("%Y") %></p>
      <p class="sp-fontsize-p"><%= @record.genre %></p>
      <p class="sp-fontsize-p"><%= @record.introduction %></p>
    </div>
  </div>
  <div class="row mt-5 mb-5">
    <div class="col-6 text-center">
      <%= form_with model:[@record, @post_comment] do |f| %>
        <%= f.text_area :comment, rows:'5', placeholder: "コメント", class: "border-0 rounded comment-form" %>
        <%= f.submit "送信", class: "btn btn-outline-light btn-sm" %>
      <% end %>
    </div>
    <div class="col-6 text-white" id="post_comment_<%= @record.id %>">
      <%= render  partial: 'post_comments/post_comment', locals: { post_comments: @post_comments } %>
    </div>
  </div>




</div>

app/views/rooms/index.html.erb
<div class="main-container bg-color">
  <h2>メッセージ一覧</h2>
  <% @another_entries.each do |another_entry| %>
    <table class="table table-striped dm-table">
      <tr>
        <td>
          <%= link_to room_path(another_entry.room.id) do %>
            <%= attachment_image_tag another_entry.end_user, :profile_image, fallback: "no-image.png", size: '60x60', class: "rounded-circle" %></br>
          <% end %>
          <%= link_to another_entry.end_user.name, room_path(another_entry.room.id) %>
        </td>
        <td class="text-white">
          <!-- 最新メッセージ内容の最初の7文字を表示する -->
          <% if another_entry.room.direct_message_ids.present? %>
            <% dm = DirectMessage.find_by(id: another_entry.room.direct_message_ids.last).message %>
            <p class="d-message"><%= truncate(dm, length: 10) %></p>
          <% else %>
            <p class="text-danger d-message">メッセージを送信しまよう</p>
          <% end %>
        </td>
        <td>
          <%= link_to room_path(another_entry.room.id), method: :delete do %>
            <i class="fas fa-trash d-delete" style="color: white;"></i>
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="main-container text-white">
  <% @entries.each do |entry| %>
    <% current_end_user == entry.end_user ? @class = "current_end_user" : @class = "" %>
    <% if entry.end_user != current_end_user %>
      <h5 class="text-center <%= @class %>" id="<%= @class %>" style="font-size: 30px;" data-id="<%= entry.end_user.id %>">
        <%= link_to "#{entry.end_user.name}", end_user_path(entry.end_user_id), class: "text-white" %>
      </h5>
    <% else %>
      <h5 class="text-left <%= @class %>" id="<%= @class %>" data-id="<%= entry.end_user.id %>"></h5>
    <% end %>
  <% end %>

   <!--me内容は部分テンプレートにします-->
  <div class="dm-wrapper" id="direct_messages" data-room_id="<%= @room.id %>">
    <%= render @direct_messages %>
  </div>
  <div class="text-center">
    <form>
        <label style="color: white;" id="target">新しいメッセージを作成</label><br>
        <input type="text" id="chat-input" data-behavior="room_speaker" class="col-form-label border-0 rounded-pill col-sm-6 mt-3">
    </form>
  </div>

</div>

<script>
  //トークルームに入室すると一番下までスクロールする
  var element = document.getElementById('target');
  var rect = element.getBoundingClientRect();
  var position = rect.top;
  setTimeout( function() {
    scrollTo(0, position);}
  , 1000);
</script>