config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'terms_of_use' => 'homes#terms_of_use'
  devise_for :end_users
  resources :end_users, only: [:index, :show, :edit, :update] do
    member do
      get 'mypage/:id' => 'end_users#mypage', as: 'mypage'
      get 'my_favorite/:id' => 'end_users#my_favorite', as: 'my_favorite'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :records, only: [:index, :show, :edit, :update, :create, :new, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :rooms

  resources :contacts, only: [:new, :create] do
    collection do
      post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
      post 'contacts/back' => 'contacts#back', as: 'back'
      get 'done' => 'contacts#done', as: 'done'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :email, presence: true
  validates :message, presence: true, length: { minimum: 2, maximum: 500 }
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :end_user
  belongs_to :room

  after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  default_scope -> { order(created_at: :desc) }

  has_many :records, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries

  # 自分がフォローされる側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー、フォロワー一覧機能実装の為
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 500 }

  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  # end_userのindexページで検索
  def self.search(keyword)
    if keyword == ''
      all
    else
      where(["name like?", "%#{keyword}%"])
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :record
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user
  belongs_to :record

  validates :comment, presence: true, length: { minimum: 1, maximum: 100 }
end

app/models/record.rb
class Record < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :artist_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :genre, presence: true
  validates :introduction, presence: true, length: { minimum: 2, maximum: 500 }
  validates :release_date, presence: true

  attachment :image

  enum genre: { pops: 0, rock: 1, black_music: 2, edm: 3, classic: 4, jazz: 5 }

  # いいね済みかどうか確認する
  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  # def self.record_search(keyword)
  #   where(["title like? OR introduction like? OR artist_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  # end

  # rcordのindexページの検索
  def self.search(keyword)
    if keyword == ''
      all
    else
      where(["title like? OR introduction like? OR artist_name like? OR genre like? OR release_date like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :end_users, through: :entries
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if end_user_signed_in?
      redirect_to mypage_path(current_end_user.id)
    end
  end

  def terms_of_use
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_end_user!

  def index
    @end_user = current_end_user
    @current_entries = @end_user.entries.includes([:room])
    my_room_ids = []
    @current_entries.each do |entry|
      my_room_ids << entry.room.id
    end
    @another_entries =
      Entry.includes([:room, :end_user]).where(room_id: my_room_ids).where.not(end_user_id: @end_user.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:end_user_id => current_end_user.id, :room_id => @room.id).present?
      @direct_messages = @room.direct_messages.includes([:end_user])
      @entries = @room.entries.includes([:end_user])
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(:name => "DM")
    @entry1 = Entry.create(:room_id => @room.id, :end_user_id => current_end_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:end_user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room.id)
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to request.referer
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/contacts/_error_message.html.erb
  <div class="error-message mt-3">
    <% if @contact.errors.any? %>
      入力内容を確認してください
    <% end %>
  </div>

app/views/contacts/confirm.html.erb
<div class="text-center text-white mt-5">
  <h2 class="mb-5">メッセージ内容確認</h2>
  <h5 class="contact-content">お名前</h5>
  <h5 class="contact-content"><%= @contact.name %></h5></br>
  <h5 class="contact-content">メッセージ</h5>
  <h5 class="contact-content"><%= @contact.message %></h5>
      </tr>
    </tbody>
  </table>

  <%= form_with model: @contact, local: true do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :message %>
    <%= f.submit '送信', class: "btn btn-outline-light mt-5" %>
  <% end %>
  <%= form_with model: @contact, url: back_contacts_path, local: true do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :message %>
    <div><%= f.submit '入力画面に戻る', class: "btn btn-outline-light mt-3" %></div>
  <% end %>
</div>

app/views/contacts/done.html.erb
<div class="container text-center pt-5">
  <h2 class="contact-finish">送信完了</h2>
  <p>
    <% if end_user_signed_in? %>
      <%= link_to "mypageへ戻る", mypage_end_user_path(current_end_user.id), class: "btn btn-outline-light" %>
    <% else %>
      <%= link_to "ホームへ戻る", "/", class: "btn btn-outline-light" %>
    <% end %>
  </p>
</div>

app/views/contacts/new.html.erb
<div class="container text-center mt-5 contact-form">
  <h2>お問い合わせフォーム</h2>

  <%= render 'contacts/error_message' %>

  <%= form_with model: @contact, url: confirm_contacts_path, local: true do |f| %>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_field :name, autofocus: true, placeholder: "名前", class: 'col-form-label rounded-pill col-sm-6' %>
    </div>

    <div class="form-group form-group-lg mt-5">
      <%= f.text_field :email, placeholder: "メール", class: 'col-form-label rounded-pill col-sm-6' %>
    </div>

    <div class="form-group form-group-lg mt-5">
      <%= f.text_area :message, placeholder: "お問い合わせ内容", size: '10x10', class: 'col-form-label rounded col-sm-6 mb-5' %>
    </div>

    <div>
      <%= f.submit '入力内容確認', class: "btn btn-outline-light" %>
    </div>
  <% end %>
</div>