config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'terms_of_use' => 'homes#terms_of_use'
  devise_for :end_users
  resources :end_users, only: [:index, :show, :edit, :update] do
    member do
      get 'mypage/:id' => 'end_users#mypage', as: 'mypage'
      get 'my_favorite/:id' => 'end_users#my_favorite', as: 'my_favorite'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :records, only: [:index, :show, :edit, :update, :create, :new, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :rooms

  resources :contacts, only: [:new, :create] do
    collection do
      post 'contacts/confirm' => 'contacts#confirm', as: 'confirm'
      post 'contacts/back' => 'contacts#back', as: 'back'
      get 'done' => 'contacts#done', as: 'done'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :email, presence: true
  validates :message, presence: true, length: { minimum: 2, maximum: 500 }
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :end_user
  belongs_to :room

  after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  default_scope -> { order(created_at: :desc) }

  has_many :records, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries

  # 自分がフォローされる側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー、フォロワー一覧機能実装の為
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 500 }

  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  # end_userのindexページで検索
  def self.search(keyword)
    if keyword == ''
      all
    else
      where(["name like?", "%#{keyword}%"])
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :record
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user
  belongs_to :record

  validates :comment, presence: true, length: { minimum: 1, maximum: 100 }
end

app/models/record.rb
class Record < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :end_user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :artist_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :genre, presence: true
  validates :introduction, presence: true, length: { minimum: 2, maximum: 500 }
  validates :release_date, presence: true

  attachment :image

  enum genre: { pops: 0, rock: 1, black_music: 2, edm: 3, classic: 4, jazz: 5 }

  # いいね済みかどうか確認する
  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  # def self.record_search(keyword)
  #   where(["title like? OR introduction like? OR artist_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  # end

  # rcordのindexページの検索
  def self.search(keyword)
    if keyword == ''
      all
    else
      where(["title like? OR introduction like? OR artist_name like? OR genre like? OR release_date like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :end_users, through: :entries
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :authenticate_end_user!
  before_action :ensure_correct_user, only: [:edit, :update, :my_favorite]

  def mypage
    @end_user = EndUser.find(params[:id])
    @records = @end_user.records
  end

  def index
    keyword = params[:keyword]
    # end_userの検索結果を表示（current_end_userは表示しない）
    @end_users = EndUser.search(keyword).where.not(id: current_end_user.id)
  end

  def show
    @end_user = EndUser.find(params[:id])
    @records = @end_user.records.limit(6)
    @my_favorites = @end_user.favorites.includes([:record])
    # DM機能
    @room_id = (@end_user.entries.pluck(:room_id) & current_end_user.entries.pluck(:room_id)).first
    @room, @entry = Room.new, Entry.new unless @room_id
  end

  # current_end_userのお気に入り一覧ページ
  def my_favorite
    @end_user = EndUser.find(params[:id])
    favorites = Favorite.where(end_user_id: @end_user.id).pluck(:record_id)
    @favorite_records = Record.find(favorites)
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    @end_user.update(end_user_params) ? (redirect_to end_user_path(@end_user.id)) : (render :edit)
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name, :introduction, :email, :profile_image)
  end

  def ensure_correct_user
    @end_user = EndUser.find(params[:id])
    if @end_user != current_end_user
      redirect_to mypage_path(current_end_user.id)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if end_user_signed_in?
      redirect_to mypage_path(current_end_user.id)
    end
  end

  def terms_of_use
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_end_user!

  def index
    @end_user = current_end_user
    @current_entries = @end_user.entries.includes([:room])
    my_room_ids = []
    @current_entries.each do |entry|
      my_room_ids << entry.room.id
    end
    @another_entries =
      Entry.includes([:room, :end_user]).where(room_id: my_room_ids).where.not(end_user_id: @end_user.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:end_user_id => current_end_user.id, :room_id => @room.id).present?
      @direct_messages = @room.direct_messages.includes([:end_user])
      @entries = @room.entries.includes([:end_user])
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(:name => "DM")
    @entry1 = Entry.create(:room_id => @room.id, :end_user_id => current_end_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:end_user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room.id)
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to request.referer
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/end_users/_error_message.html.erb
  <div class="error-message">
    <% if @end_user.errors.any? %>
      入力内容を確認してください
    <% end %>
  </div>

app/views/end_users/_index.html.erb
  <% end_users.each do |end_user| %>e
    <div class="text-white mt-3 d-flex justify-content-around end-user-item">
      <div class="mr-1">
        <%= link_to end_user_path(end_user.id) do %>
          <%= attachment_image_tag end_user, :profile_image, fallback: "no-image2.jpg", size: '60x60', class: "rounded-circle" %>
        <% end %>
      </div>
      <div class="mr-3"><%= link_to end_user.name, end_user_path(end_user.id) %></div>
      <div id="follow_btns_<%= end_user.id %>" class="mr-2">
        <%= render partial: 'relationships/follows', locals: { end_user: end_user } %>
      </div>
    </div>
  <% end %>

app/views/end_users/edit.html.erb
<div class="main-container text-white text-center">

  <%= render 'end_users/error_message' %>

 <%= form_with model: @end_user, local: true do |f| %>
   <div class="form-group form-group-lg mt-5 text-center">
     <p><img id="preview"></p>
     <p><%= attachment_image_tag @end_user, :profile_image, fallback: "no-image2.jpg", size: '200x150', id: "existing_file" %></p>
     <p><%= f.attachment_field :profile_image %></p>
   </div>
   <div class="form-group form-group-lg mt-5">
      <%= f.text_field :name, class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.text_area :introduction, class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div class="form-group form-group-lg mt-5">
      <%= f.email_field :email, class: "col-form-label rounded-pill col-sm-6" %>
    </div>
    <div>
      <%= image_submit_tag("change-icon.png", id: "edit_end_user_button") %>
    </div>
 <% end %>
</div>

<script>
  $('#end_user_profile_image').on('change', function (e) {
    let reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
        $("#existing_file").hide();
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/end_users/index.html.erb
<div class="text-left main-container">
  <h4 class="text-center mb-3"><%= link_to "レコード一覧", records_path, class: "text-white" %></h4>
  <%= form_with url: end_users_path, method: :get, local: true do |f| %>
    <div class="text-right form-group form-group-lg">
      <%= f.text_field :keyword, value: @keyword, class: "col-form-label border-0 rounded-pill col-sm-4 search_word" %>
      <%= f.submit "検索", class: "btn btn-outline-light search-btn" %>
    </div>
  <% end %>
  <div class="search-enduser end-user-index">
    <%= render 'index', end_users: @end_users %>
  </div>

</div>

app/views/end_users/index.js.erb
$('.search-enduser').html('<%= j(render 'index', end_users: @end_users) %>');

app/views/end_users/my_favorite.html.erb
<div class="main-container text-center">
  <h3>お気に入り一覧</h3>
  <div class="d-flex justify-content-center align-content-start flex-wrap">
    <% @favorite_records.each do |favorites_record| %>
      <%= link_to record_path(favorites_record.id), class: "my-record" do %>
       <%= attachment_image_tag favorites_record, :image, fallback: "no-image.png", size:'200x200', class: "m-1 record record-image" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/end_users/mypage.html.erb
<div class="main-container">
  <div class="text-center mb-3 new-collection">
    <% if @end_user == current_end_user %>
      <%= link_to image_tag("new-collection.png"), new_record_path, class: "img-fluid new-collection-icon" %>
    <% else %>
      <%= link_to end_user_path(@end_user.id) , class: "mr-3" do %>
        <%= attachment_image_tag @end_user, :profile_image, fallback: "no-image.png", size: '100x100', class: "rounded-circle" %>
      <% end %>
    <% end %>
  </div>
  <div class="mb-5 d-flex justify-content-center flex-wrap">
    <% @records.each do |record| %>
      <%= link_to record_path(record.id), class: "my-record" do %>
        <%= attachment_image_tag record, :image, fallback: "no-image.png", size:'200x200', class: "m-1 shadow" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/end_users/show.html.erb
<div class="user-show main-container">
  <div class="text-center">
    <h1>profile</h1>
  </div>
  <div class="row">
    <div class="col-4 text-center mt-3">
      <p><%= attachment_image_tag @end_user, :profile_image, fallback: "no-image2.jpg", size:'180x180', class: "rounded-circle profile-image" %></p>
      <h2 class="d-inline"><%= @end_user.name %></h2>
      <!--他人のプロフィールを見る場合-->
      <% if @end_user.id != current_end_user.id %>
        <!--フォローボタンを部分テンプレートとして読み込む-->
        <div id="follow_btns_<%= @end_user.id %>">
          <%= render partial: 'relationships/follows', locals: { end_user: @end_user } %>
        </div>
      <!--自分のプロフィールを見る場合-->
      <% else %>
        <div class="mt-1"><%= link_to "編集", edit_end_user_path(@end_user.id), class: "text-white" %></div>
      <% end %>
      <p class="mt-3 text-white introduction"><%= @end_user.introduction %></p>
      <div>
        <p><%= link_to "フォロー", end_user_followings_path(@end_user.id), class: "text-white follow" %></p>
        <p><%= link_to "フォロワー", end_user_followers_path(@end_user.id), class: "text-white follower" %></p>
      </div>
      <div class="mt-3">
        <% unless @end_user.id == current_end_user.id %>
          <!--ルームが存在していれば既存のルームへのリンクを表示-->
          <% if @room_id %>
            <%= link_to room_path(@room_id) do %>
              <i class="fas fa-envelope h3"></i>
            <% end %>
          <!--ルームが存在していなければルームを作成するリンクを表示  -->
          <% else %>
            <%= form_with model: @room, url: rooms_path do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :end_user_id, :value=> @end_user.id %>
              <% end %>
              <button type="submit" id="dm_submit"><i class="fas fa-envelope h3"></i></button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-8 mt-3">
      <!--自分のプロフィールを見る場合自分のお気に入り登録したレコードを表示する-->
      <% if @end_user.id == current_end_user.id %>
        <h2 class="text-center">my favorites</h2>
        <% @my_favorites.each do |my_favorite| %>
          <%= link_to record_path(my_favorite.record.id) do %>
            <%= attachment_image_tag my_favorite.record, :image, fallback: "no-image.png", size:'200x200', class: "m-1 record-image" %>
          <% end %>
        <% end %>
        <div class="text-right">
          <%= link_to "お気に入り一覧へ", my_favorite_end_user_path(@end_user.id), class: "text-white" %>
        </div>
      <!--他人のプロフィールを見る場合その人のレコードの新着を6件表示する-->
      <% else %>
        <h2 class="text-center responsive-title">Records</h2>
        <% @records.each do |record| %>
          <%= link_to record_path(record.id) do %>
            <%= attachment_image_tag record, :image, fallback: "no-image.png", size:'200x200', class: "m-1 record-image" %>
          <% end %>
        <% end %>
        <div class="text-right">
          <p><%= link_to "レコード一覧へ", mypage_end_user_path(@end_user.id), class: "text-white" %></p>
        </div>

      <% end %>
    </div>
  </div>
</div>